#!/usr/bin/sh

setxkbmap gb
xset r rate 200 80
xset s off -dpms
xsetroot -cursor_name miku-cursor-linux

# xgfxtablet

# multi-monitor
xrandr --output HDMI-1 --primary --output HDMI-2 --right-of HDMI-1
