[window]
dynamic_title = true

[font]
size = 12.0

[font.bold]
# family = "JetBrainsMono Nerd Font Mono"
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.bold_italic]
# family = "JetBrainsMono Nerd Font Mono"
family = "Iosevka Nerd Font Mono"
style = "Bold Italic"

[font.italic]
# family = "JetBrainsMono Nerd Font Mono"
family = "Iosevka Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "JetBrainsMono Nerd Font Mono"
family = "Iosevka Nerd Font Mono"
style = "Regular"

[colors]

[colors.primary]
foreground = "#f5f5f5"
background = "#000000"

[colors.normal]
black = "#000000"
red = "#ff4040"
green = "#40ff40"
yellow = "#ffff40"
blue = "#4040ff"
magenta = "#ff40ff"
cyan = "#40ffff"
white = "#f5f5f5"

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 250
blink_timeout = 0

